"""Increase length of password

Revision ID: 955d93d3efe3
Revises: 600b4fea079a
Create Date: 2024-10-18 16:15:14.972706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955d93d3efe3'
down_revision = '600b4fea079a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
